#组件信息
component: scf # (必选) 组件名称，在该实例中为 scf
name: dailycheckin # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: ${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler # 入口
  runtime: Python3.6 # 运行环境
  region: ap-hongkong # 函数所在区域
  description: 每日签到集合 - ${app}
  memorySize: 128 # 内存大小，单位 MB
  timeout: 900 # 超时时间，单位秒
  events: # 触发器
    - timer: # 日常签到签到
        parameters:
          name: dailycheckin
          cronExpression: "0 45 8 * * * *"
          enable: true
          argument: None
    - timer: # 喜马拉雅极速版
        parameters:
          name: xmly
          cronExpression: "0 */30 * * * * *"
          enable: true
          argument: xmly
